language: python
dist: xenial
sudo: false
python:
- '3.6'
- '3.7'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install .
script:
- pytest --cov=dateparse dateparse
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: AgEIcHlwaS5vcmcCJDI3NzIwYjVhLTRmM2ItNDgwNy1iMjNiLWMzZDUyNmQwNzM4MAACQ3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkYXRlcGFyc2UtdG9iaWFzbGkiXX0sICJ2ZXJzaW9uIjogMX0AAAYg4eBExKomJk5K9Q6eWUE2SbGndJKbXzjzl6N-ScFBwHc
  on:
    branch: master