language: python
dist: xenial
sudo: false
python:
- '3.6'
- '3.7'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
- pip install .
script:
- pytest --cov=dateparse dateparse
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: YBLBtVUfKpUMSo9hVAQxzzYjdo3uZZi/l/Tj9gVhPp6WXATIdQUfMOkm1aGGRRG+o3KM5ZgJLXNGvR6Ly+sHSyyy669cKobtjp14Hzh2WSOmlBsIUsKazjj8PoU1QTXKNILFQdmitwKoLmUbxIeAqRMCNRms0eEWgaRsR/JRCRJWx3lvor1GVMk4Mprks3mlrAMLM2UolYvuJjV0bvTzbYkbgL5nJiY3Gqq6EkH69oCxV7IRYIGVhUxo+AvbGjesAKLxVco10rSXF3AUafRvx9VYJPKZrr/OZAV2BGf0/2/x/DTmwdRKqGJucLcA13Y/UqpWyTeZfIlY45lXXpqL1/6OScK5IoICT8cf0QkEyL+pPx0aPDZ5eBZEpRo/Vp8/QwlVEbT7YwlNPtsg2zYeC4uNOFIccIHcl4w2Fdv90QiyBoJZsSSncsfUTdtw35k9IuFCdMdi6F+sSH/q3889iAQXj21YgmPMkLvWPULBvYIIdc5uCOJZ0gr/+4YFDCJirkDjg/syTtEKUHJCGbfFv+PUpEfNW4Nj4RRfZSWVG+3Ban56d6W4ZKQaZlbPrWMzweZyAOaXhSIN3y36iahzqAYRi4Smrd/FDCxDNq/9ZJSVANZf4DrbApkwHwpQ8KsJXvxFvIMbMHmC6+E5Mh8yBP3i6TjT40d3AM88a/gFYcw=
  on:
    branch: master
